export enum GAME_VERSION_STATUS {
  PREPARE_FOR_SUBMISSION = 'PREPARE_FOR_SUBMISSION',
  READY_FOR_DISTRIBUTION = 'READY_FOR_DISTRIBUTION',
  IN_REVIEW = 'IN_REVIEW',
  CURRENT = 'CURRENT',
  REJECTED = 'REJECTED',
  ARCHIVED = 'ARCHIVED',
}