export enum GAME_VERSION_STATUS {
  PREPARE_FOR_SUBMISSION = "PREPARE_FOR_SUBMISSION",
  READY_FOR_DISTRIBUTION = "READY_FOR_DISTRIBUTION",
  IN_REVIEW = "IN_REVIEW",
  CURRENT = "CURRENT",
  REJECTED = "REJECTED",
  ARCHIVED = "ARCHIVED",
}

export enum COLORS {
  BRAND = "BRAND",
  NEUTRAL = "NEUTRAL",
  POSITIVE = "POSITIVE",
  WARNING = "WARNING",
  NEGATIVE = "NEGATIVE",
}

export enum TIME_FORMAT {
  BE_TIME = "yyyy-MM-dd",
  FE_TIME = "dd-MM-yyyy",
  FULL_TIME = "MM/dd/yyyy hh:mm a",
  YEAR = "yyyy",
}
